version: "3.9"

services:

  grpc-server:
    image: hubviwe/grpc.server:1.0.0
    hostname: localhost
    build:
        context: src/
        dockerfile: Server/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5007:80
